//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LojaOlharDeMenina_WPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estoque
    {
        public int ID { get; set; }
        public int FK_CodigoProduto { get; set; }
        public int NumLote { get; set; }
        public int TotalProdutos { get; set; }
        public Nullable<decimal> Frete { get; set; }
        public string Fornecedor { get; set; }
        public System.DateTime DataCompra { get; set; }
        public int Quantidade { get; set; }
        public decimal PrecoCusto { get; set; }
        public System.DateTime Validade { get; set; }
    
        public virtual Produto Produto { get; set; }
    }
}
