//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LojaOlharDeMenina_WPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendaDetalhes
    {
        public int Codigo { get; set; }
        public int FK_CodigoVendas { get; set; }
        public int FK_CodigoProduto { get; set; }
        public int Quantidade { get; set; }
    
        public virtual Produtos Produtos { get; set; }
        public virtual Venda Venda { get; set; }
    }
}
